version: '3.3'

services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "7788:7788"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "9009:9009"
    depends_on:
      - django_gunicorn

volumes:
  static: